#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

(new \Symfony\Component\Dotenv\Dotenv)->load(__DIR__ . '/.env');

$application = new Symfony\Component\Console\Application();
$application->add(new \LaravelNewsVkCommunity\Commands\CheckRssCommand);
$application->add(new \LaravelNewsVkCommunity\Commands\MigrateCommand);
$application->add(new \LaravelNewsVkCommunity\Commands\UnpublishedPostsCommand);
$application->add(new \LaravelNewsVkCommunity\Commands\PostCommand);
$application->run();