#!/usr/bin/env php
<?php

ini_set('display_errors', 1);
error_reporting(E_ALL);

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new \LaravelNewsVkCommunity\Commands\CheckRssCommand);
$application->add(new \LaravelNewsVkCommunity\Commands\MigrateCommand);
$application->add(new \LaravelNewsVkCommunity\Commands\PostCommand);

$application->run();